# Generated by Django 2.2 on 2020-08-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='_type',
            new_name='type_of_prog',
        ),
    ]
