# Generated by Django 2.2 on 2020-08-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0007_auto_20200822_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
