# Generated by Django 2.2 on 2020-08-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0009_rhemawordfortoday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhemawordfortoday',
            name='content',
            field=models.TextField(),
        ),
    ]
