# Generated by Django 2.2 on 2020-09-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0010_auto_20200822_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='duration_from',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='duration_to',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='time_to',
        ),
        migrations.AddField(
            model_name='programme',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
