# Generated by Django 2.2 on 2020-09-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0011_auto_20200904_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='date',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='time',
        ),
    ]
