# Generated by Django 2.2 on 2020-09-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0012_auto_20200904_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='programme',
            name='post_tag',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='type_of_prog',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.AddField(
            model_name='programme',
            name='programme_category',
            field=models.ManyToManyField(blank=True, to='ministry.Category'),
        ),
    ]
